// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/falcon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FalconService_RegisterEdge_FullMethodName = "/falcon.FalconService/RegisterEdge"
)

// FalconServiceClient is the client API for FalconService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- SERVICE ----------
type FalconServiceClient interface {
	RegisterEdge(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type falconServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFalconServiceClient(cc grpc.ClientConnInterface) FalconServiceClient {
	return &falconServiceClient{cc}
}

func (c *falconServiceClient) RegisterEdge(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, FalconService_RegisterEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FalconServiceServer is the server API for FalconService service.
// All implementations must embed UnimplementedFalconServiceServer
// for forward compatibility.
//
// ---------- SERVICE ----------
type FalconServiceServer interface {
	RegisterEdge(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedFalconServiceServer()
}

// UnimplementedFalconServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFalconServiceServer struct{}

func (UnimplementedFalconServiceServer) RegisterEdge(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEdge not implemented")
}
func (UnimplementedFalconServiceServer) mustEmbedUnimplementedFalconServiceServer() {}
func (UnimplementedFalconServiceServer) testEmbeddedByValue()                       {}

// UnsafeFalconServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FalconServiceServer will
// result in compilation errors.
type UnsafeFalconServiceServer interface {
	mustEmbedUnimplementedFalconServiceServer()
}

func RegisterFalconServiceServer(s grpc.ServiceRegistrar, srv FalconServiceServer) {
	// If the following call panics, it indicates UnimplementedFalconServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FalconService_ServiceDesc, srv)
}

func _FalconService_RegisterEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FalconServiceServer).RegisterEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FalconService_RegisterEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FalconServiceServer).RegisterEdge(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FalconService_ServiceDesc is the grpc.ServiceDesc for FalconService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FalconService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "falcon.FalconService",
	HandlerType: (*FalconServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEdge",
			Handler:    _FalconService_RegisterEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/falcon.proto",
}
