// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/falcon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Registering edge
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_falcon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_falcon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Edge Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_falcon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_falcon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// File chunk details
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_falcon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{4}
}

func (x *FileChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileChunk) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileChunk) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type TransferStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // success | failed | running
	ReceivedChunks int64                  `protobuf:"varint,3,opt,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferStatus) Reset() {
	*x = TransferStatus{}
	mi := &file_proto_falcon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatus) ProtoMessage() {}

func (x *TransferStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatus.ProtoReflect.Descriptor instead.
func (*TransferStatus) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{5}
}

func (x *TransferStatus) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferStatus) GetReceivedChunks() int64 {
	if x != nil {
		return x.ReceivedChunks
	}
	return 0
}

// Recording mount details to DB
type StorageReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,5,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	Writable      bool                   `protobuf:"varint,6,opt,name=writable,proto3" json:"writable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageReport) Reset() {
	*x = StorageReport{}
	mi := &file_proto_falcon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageReport) ProtoMessage() {}

func (x *StorageReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageReport.ProtoReflect.Descriptor instead.
func (*StorageReport) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{6}
}

func (x *StorageReport) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *StorageReport) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *StorageReport) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StorageReport) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StorageReport) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *StorageReport) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

type StorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_proto_falcon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{7}
}

func (x *StorageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Recording file detail to DB
type FileRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt    string                 `protobuf:"bytes,5,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // NEW: created | modified | deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRecord) Reset() {
	*x = FileRecord{}
	mi := &file_proto_falcon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRecord) ProtoMessage() {}

func (x *FileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRecord.ProtoReflect.Descriptor instead.
func (*FileRecord) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{8}
}

func (x *FileRecord) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *FileRecord) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *FileRecord) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileRecord) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileRecord) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *FileRecord) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type InventoryStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FilesReceived int32                  `protobuf:"varint,2,opt,name=files_received,json=filesReceived,proto3" json:"files_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryStatus) Reset() {
	*x = InventoryStatus{}
	mi := &file_proto_falcon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryStatus) ProtoMessage() {}

func (x *InventoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_falcon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryStatus.ProtoReflect.Descriptor instead.
func (*InventoryStatus) Descriptor() ([]byte, []int) {
	return file_proto_falcon_proto_rawDescGZIP(), []int{9}
}

func (x *InventoryStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InventoryStatus) GetFilesReceived() int32 {
	if x != nil {
		return x.FilesReceived
	}
	return 0
}

var File_proto_falcon_proto protoreflect.FileDescriptor

const file_proto_falcon_proto_rawDesc = "" +
	"\n" +
	"\x12proto/falcon.proto\x12\x06falcon\"O\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"C\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x96\x01\n" +
	"\tFileChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x03R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"r\n" +
	"\x0eTransferStatus\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0freceived_chunks\x18\x03 \x01(\x03R\x0ereceivedChunks\"\xc2\x01\n" +
	"\rStorageReport\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x05 \x01(\x04R\tfreeBytes\x12\x1a\n" +
	"\bwritable\x18\x06 \x01(\bR\bwritable\")\n" +
	"\x0fStorageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xbb\x01\n" +
	"\n" +
	"FileRecord\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x05 \x01(\tR\n" +
	"modifiedAt\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\"R\n" +
	"\x0fInventoryStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0efiles_received\x18\x02 \x01(\x05R\rfilesReceived2\x97\x02\n" +
	"\rFalconService\x12A\n" +
	"\fRegisterEdge\x12\x17.falcon.RegisterRequest\x1a\x18.falcon.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.falcon.HeartbeatRequest\x1a\x19.falcon.HeartbeatResponse\x12?\n" +
	"\rReportStorage\x12\x15.falcon.StorageReport\x1a\x17.falcon.StorageResponse\x12@\n" +
	"\x0fUploadInventory\x12\x12.falcon.FileRecord\x1a\x17.falcon.InventoryStatus(\x012N\n" +
	"\x0fTransferService\x12;\n" +
	"\fTransferFile\x12\x11.falcon.FileChunk\x1a\x16.falcon.TransferStatus(\x01B+Z)github.com/sooraj-zebu/falcon/proto;protob\x06proto3"

var (
	file_proto_falcon_proto_rawDescOnce sync.Once
	file_proto_falcon_proto_rawDescData []byte
)

func file_proto_falcon_proto_rawDescGZIP() []byte {
	file_proto_falcon_proto_rawDescOnce.Do(func() {
		file_proto_falcon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_falcon_proto_rawDesc), len(file_proto_falcon_proto_rawDesc)))
	})
	return file_proto_falcon_proto_rawDescData
}

var file_proto_falcon_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_falcon_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: falcon.RegisterRequest
	(*RegisterResponse)(nil),  // 1: falcon.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: falcon.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: falcon.HeartbeatResponse
	(*FileChunk)(nil),         // 4: falcon.FileChunk
	(*TransferStatus)(nil),    // 5: falcon.TransferStatus
	(*StorageReport)(nil),     // 6: falcon.StorageReport
	(*StorageResponse)(nil),   // 7: falcon.StorageResponse
	(*FileRecord)(nil),        // 8: falcon.FileRecord
	(*InventoryStatus)(nil),   // 9: falcon.InventoryStatus
}
var file_proto_falcon_proto_depIdxs = []int32{
	0, // 0: falcon.FalconService.RegisterEdge:input_type -> falcon.RegisterRequest
	2, // 1: falcon.FalconService.Heartbeat:input_type -> falcon.HeartbeatRequest
	6, // 2: falcon.FalconService.ReportStorage:input_type -> falcon.StorageReport
	8, // 3: falcon.FalconService.UploadInventory:input_type -> falcon.FileRecord
	4, // 4: falcon.TransferService.TransferFile:input_type -> falcon.FileChunk
	1, // 5: falcon.FalconService.RegisterEdge:output_type -> falcon.RegisterResponse
	3, // 6: falcon.FalconService.Heartbeat:output_type -> falcon.HeartbeatResponse
	7, // 7: falcon.FalconService.ReportStorage:output_type -> falcon.StorageResponse
	9, // 8: falcon.FalconService.UploadInventory:output_type -> falcon.InventoryStatus
	5, // 9: falcon.TransferService.TransferFile:output_type -> falcon.TransferStatus
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_falcon_proto_init() }
func file_proto_falcon_proto_init() {
	if File_proto_falcon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_falcon_proto_rawDesc), len(file_proto_falcon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_falcon_proto_goTypes,
		DependencyIndexes: file_proto_falcon_proto_depIdxs,
		MessageInfos:      file_proto_falcon_proto_msgTypes,
	}.Build()
	File_proto_falcon_proto = out.File
	file_proto_falcon_proto_goTypes = nil
	file_proto_falcon_proto_depIdxs = nil
}
