app:
  name: Falcon Core
  version: 1.0.0

server:
  http_port: 12166
  grpc_port: 12167

core:
  host: 127.0.0.1

logging:
  level: info

storage:
  data_dir: /Users/sooraj/Desktop/Falcon/Falcon/db
  log_dir: /Users/sooraj/Desktop/Falcon/Falcon/db/
