app:
  name: Falcon Edge
  version: 1.0.0

edge:
  name: falcon-edge-tvm

server:
  http_port: 12168
  grpc_port: 12169

core:
  host: 127.0.0.1
  http_port: 12166
  grpc_port: 12167

logging:
  level: info

storage:
  data_dir: data
  log_dir: logs
  mount_path: /root/Falcon/dev-storage
