app:
  name: Falcon Edge
  version: 1.0.0

edge:
  name: falcon-edge-
  disable_auto_sync: true

core:
  host: 43.241.70.134
  grpc_port: 12167

logging:
  level: info

storage:
  data_dir: /opt/falcon/data
  log_dir: /opt/falcon/logs
  mount_path: /mnt/storage
